#!/usr/bin/env bash
# Data platform for one stage: the PostgreSQL server (database.bicep), its roles (azure-roles.sql) and
# the sign-in, REST, realtime, storage and gateway services (platform.bicep).
#
#   ./infra/platform.sh --stage test        (or live; default live)
#
# Secrets come from infra/platform.<stage>.env (gitignored, generated once with --init, never printed).
# Re-running is safe: every step is idempotent. The app's own schema is loaded separately with
# scripts/db-bootstrap.sh once the services have created theirs (docs/DEPLOYMENT.md §2.2).
set -euo pipefail
INFRA_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$INFRA_DIR/.." && pwd)"
STAGE="${STAGE:-live}"; INIT=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --stage) STAGE="$2"; shift ;;
    --stage=*) STAGE="${1#*=}" ;;
    --init) INIT=1 ;;
    -h|--help) sed -n '2,9p' "$0"; exit 0 ;;
    *) echo "unknown option $1" >&2; exit 1 ;;
  esac; shift
done
export STAGE
# shellcheck source=lib.sh
source "$INFRA_DIR/lib.sh"
load_azure_env
require_az_login
P="$( [[ "$STAGE" == live ]] && echo "$PREFIX" || echo "$PREFIX-test" )"
PF="$INFRA_DIR/platform.$STAGE.env"

if [[ ! -f "$PF" ]]; then
  [[ $INIT -eq 1 ]] || die "$PF is missing: run with --init once to generate this stage's passwords and keys"
  ( umask 077
    r() { openssl rand -hex 24; }
    JWT="$(openssl rand -hex 32)"
    sign() { JWT_SECRET="$JWT" ROLE="$1" node -e 'const c=require("crypto");const b=o=>Buffer.from(JSON.stringify(o)).toString("base64url");const h=b({alg:"HS256",typ:"JWT"});const p=b({iss:"margix",role:process.env.ROLE,iat:1790000000,exp:2105000000});process.stdout.write(h+"."+p+"."+c.createHmac("sha256",process.env.JWT_SECRET).update(h+"."+p).digest("base64url"))'; }
    cat > "$PF" <<EOF
# This stage's database and platform secrets. Generated by infra/platform.sh --init. Never commit, never print.
PG_ADMIN_USER=margixadmin
PG_ADMIN_PASSWORD=$(r)
JWT_SECRET=$JWT
ANON_KEY=$(sign anon)
SERVICE_ROLE_KEY=$(sign service_role)
AUTHENTICATOR_PASSWORD=$(r)
AUTH_ADMIN_PASSWORD=$(r)
STORAGE_ADMIN_PASSWORD=$(r)
REALTIME_ADMIN_PASSWORD=$(r)
REALTIME_SECRET_KEY_BASE=$(openssl rand -hex 32)
EOF
  )
  log "Generated $PF"
fi
set -a; # shellcheck disable=SC1090
source "$PF"; set +a

PG_SERVER="$P-pg"
log "PostgreSQL server $PG_SERVER"
IP="$(curl -4 -s ifconfig.me || true)"
PG_HOST="$(az deployment group create -g "$RG" -n "$PG_SERVER" --template-file "$INFRA_DIR/database.bicep" \
  --parameters serverName="$PG_SERVER" location="$LOCATION" adminLogin="$PG_ADMIN_USER" adminPassword="$PG_ADMIN_PASSWORD" setupClientIp="$IP" \
  --only-show-errors --query properties.outputs.host.value -o tsv)"
if [[ "$(az postgres flexible-server parameter show -g "$RG" -s "$PG_SERVER" -n wal_level --query isConfigPendingRestart -o tsv)" == "true" ]]; then
  log "Restarting $PG_SERVER for logical replication"; az postgres flexible-server restart -g "$RG" -n "$PG_SERVER" -o none
fi

PSQL=(docker run --rm -i -e PGPASSWORD="$PG_ADMIN_PASSWORD" postgres:18-alpine psql "host=$PG_HOST port=5432 dbname=postgres user=$PG_ADMIN_USER sslmode=require" -q)
log "Roles and schemas"
"${PSQL[@]}" -v authenticator_pw="$AUTHENTICATOR_PASSWORD" -v auth_admin_pw="$AUTH_ADMIN_PASSWORD" \
  -v storage_admin_pw="$STORAGE_ADMIN_PASSWORD" -v realtime_admin_pw="$REALTIME_ADMIN_PASSWORD" \
  < "$ROOT_DIR/supabase/bootstrap/azure-roles.sql" >/dev/null

WEB_HOST="$(az staticwebapp show -g "$RG" -n "$WEB_APP" --query defaultHostname -o tsv)"
SITE_URL="https://${CUSTOM_DOMAIN:-$WEB_HOST}"
log "Services ($P-gateway, -auth, -rest, -rt, -storage); sign-in redirects to $SITE_URL"
GATEWAY="$(az deployment group create -g "$RG" -n "$P-platform" --template-file "$INFRA_DIR/platform.bicep" \
  --parameters stage="$STAGE" prefix="$PREFIX" location="$LOCATION" pgHost="$PG_HOST" siteUrl="$SITE_URL" \
    jwtSecret="$JWT_SECRET" anonKey="$ANON_KEY" serviceRoleKey="$SERVICE_ROLE_KEY" \
    authenticatorPassword="$AUTHENTICATOR_PASSWORD" authAdminPassword="$AUTH_ADMIN_PASSWORD" \
    storageAdminPassword="$STORAGE_ADMIN_PASSWORD" realtimeAdminPassword="$REALTIME_ADMIN_PASSWORD" \
    realtimeSecretKeyBase="$REALTIME_SECRET_KEY_BASE" \
  --only-show-errors --query properties.outputs.gatewayUrl.value -o tsv)"
log "Done. Gateway (the app's SUPABASE_URL for $STAGE): $GATEWAY  Database: $PG_HOST"
