-- Finance stream, part 1: invoices for delivered shipments and cargo manifests.
--
-- `invoices` and `payments` already exist (add_phone_to_users.sql). This
-- extends `invoices` instead of replacing it: adds the manifest and vendor
-- links, GST split and a total; moves money to numeric(12,2); and changes the
-- status to issued / paid / void (old rows with 'pending' become 'issued').
--
-- Number format INV-YYYYMM-#### is generated by the backend when a delivery
-- is recorded. The unique constraint on invoice_number already exists.
--
-- Additive and safe to re-run. Applied to the live project on 2026-09-29.

ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS manifest_id uuid REFERENCES public.cargo_manifest(id) ON DELETE SET NULL;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS vendor_id uuid REFERENCES public.vendor_profiles(id) ON DELETE SET NULL;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS gst_rate numeric(5,2) NOT NULL DEFAULT 0;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS gst_amount numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS total numeric(12,2);
-- Where the amount came from: 'bid' (accepted bid) or 'vendor_request' (agreed cost)
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS price_source text;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS voided_at timestamptz;

ALTER TABLE public.invoices ALTER COLUMN amount TYPE numeric(12,2);
ALTER TABLE public.invoices ALTER COLUMN status SET DEFAULT 'issued';
UPDATE public.invoices SET status = 'issued' WHERE status IS NULL OR status NOT IN ('issued', 'paid', 'void');
UPDATE public.invoices SET total = amount + gst_amount WHERE total IS NULL;

ALTER TABLE public.invoices DROP CONSTRAINT IF EXISTS invoices_status_check;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_status_check CHECK (status IN ('issued', 'paid', 'void'));

-- One live invoice per delivery
CREATE UNIQUE INDEX IF NOT EXISTS invoices_one_per_shipment ON public.invoices (shipment_id) WHERE shipment_id IS NOT NULL AND status <> 'void';
CREATE UNIQUE INDEX IF NOT EXISTS invoices_one_per_manifest ON public.invoices (manifest_id) WHERE manifest_id IS NOT NULL AND status <> 'void';
CREATE INDEX IF NOT EXISTS idx_invoices_vendor ON public.invoices (vendor_id);
CREATE INDEX IF NOT EXISTS idx_invoices_issued_at ON public.invoices (issued_at DESC);

-- RLS (same helpers as 20260928000200_row_level_security.sql): staff read and
-- write everything, a vendor reads only their own invoices.
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS invoices_select ON public.invoices;
CREATE POLICY invoices_select ON public.invoices FOR SELECT TO authenticated
  USING (vendor_id = auth.uid() OR (SELECT public.is_staff()));
DROP POLICY IF EXISTS invoices_write_staff ON public.invoices;
CREATE POLICY invoices_write_staff ON public.invoices FOR ALL TO authenticated
  USING ((SELECT public.is_staff()))
  WITH CHECK ((SELECT public.is_staff()));

NOTIFY pgrst, 'reload schema';
